#!/bin/bash

images=$PWD/images/source # /EricFootball_crop
masks=$PWD/images/mask # /EricFootball_crop
rectdir=$PWD/images/rect # for pifuhd
output=$PWD/outputs
mkdir -p $output
docker run -it --rm --gpus all \
	-v $images:/data/images \
	-v $masks:/data/masks \
	-v $rectdir:/data/rect \
	-v $output:/output \
	pifu

# run pifuhd: 
# cd pifuhd # need to first get the _rect.txt file
# python -m apps.simple_test -r 256 --use_rect -i sample_images
# 
# python -m apps.simple_test -r 512 --use_rect -i sample_images
# from lib.colab_util import generate_video_from_obj, set_renderer, video
# renderer = set_renderer()
# generate_video_from_obj(obj_path, out_img_path, video_path, renderer)
# 
# # we cannot play a mp4 video generated by cv2
# !ffmpeg -i $video_path -vcodec libx264 $video_display_path -y -loglevel quiet
# video(video_display_path)